### ISSUE TITLE
WorldGuardRegionProtect

### ISSUE THREAD

**Issue by xXnekit101Xx** [RSTeamCore/WorldGuardRegionProtect#68]
### Server Implementation

Purpur

### Server Version

1.18.2

### Describe the bug

Выдаёт ошибки в консоль, когда пишу //set где нету региона.
А где есть регион, всё работает.
![2022-06-04_18-52-50](https://user-images.githubusercontent.com/86162017/172018997-13be8dcd-5bbf-492c-81d2-ed5cd04f1261.png)

### Steps to reproduce

- [ ] 

### Expected behaviour

Жду фикса данной проблемы!

### WorldGuardRegionProtect version

WorldGuardRegionProtect [1.18-1.18.2] 0.7.2

### Checklist

- [X] I am using the newest build from https://ci.codemc.io/job/RitaSister/job/WorldGuardRegionProtect/ and the issue still persists.

### Anything else?

Вот ещё одна ошибка.
[17:51:27] [Server thread/INFO]: nekit101 issued server command: //set
[17:51:27] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to WorldGuardRegionProtect v0.7.2
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
at java.lang.String.replace(String.java:2959) ~[?:?]
at net.ritasister.wgrp.rslibs.api.RSApi.notify(RSApi.java:169) ~[WorldGuardRegionProtect-bukkit-0.7.2.jar:?]
at net.ritasister.wgrp.listener.protect.RegionProtect.denyUseWEAndIwgCommand(RegionProtect.java:373) ~[WorldGuardRegionProtect-bukkit-0.7.2.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1628]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2381) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2200) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2181) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1628]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1628]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1628]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1628]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1628]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1628]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1628]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1628]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by RitaSister** [comment]
Fixed and improve method for checking and getting of regions for method to notify in console or for player.
